"""Has the vault moved since the index was built — the question `index_version` cannot answer.

Doc 2 §5 and PRINCIPLES.md are precise about what the version stamp buys: it converts SILENT
omission into DETECTABLE omission, and no more. Detection is not freshness. There is no watcher
on this side, so the discipline is pushed onto every consumer, and a consumer with nothing to
compare against cannot exercise it — `index_version` alone tells you what the index was built
from, never that the vault changed underneath it.

This module is the comparison. It walks the scope's vaults and asks, per note, whether the index
still agrees with the disk.

**It reads `source_path`, not `markdown_path`.** Those are different files and the difference is
easy to miss: `markdown_path` is the DERIVED artifact in the disposable index root, which is
regenerated by every compose and always agrees with the index. Checking it would report a green
freshness result over a vault the user had rewritten. `source_path` is the note the user owns.

**One class of change is undetectable, and it is named rather than hidden.** The reader (Doc 2
§3b) honours a `source_sha256` declared in frontmatter — that is how a PDF-derived passage points
at the PDF it came from rather than at itself — so for those notes the stored checksum is the
PDF's, and a body edit leaves it unchanged. Rather than report those as fresh, they are counted
as `unverifiable`. A freshness report whose completeness is overstated is the failure this whole
project keeps finding; a report that names the part it could not check is not.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from substrate.markdown.reader import _SHA256, _parse_frontmatter


def effective_sha_of(data: bytes) -> tuple[str, bool]:
    """The checksum the reader WOULD store for these bytes, and whether it was declared.

    Takes bytes rather than a path so a caller that has already read the file does not read it a
    second time — two reads can straddle a write, leaving the content and the staleness verdict
    describing different versions.

    Mirrors `markdown.reader`: a well-shaped `source_sha256` in frontmatter wins, else the file's
    own checksum. Reusing the rule rather than re-deriving one is what stops this check disagreeing
    with the ingest it is auditing — two checksum rules would make every PDF passage read as
    changed, and a report full of false positives trains its reader to ignore it.
    """
    # Line endings normalized before parsing, exactly as `markdown.reader` and `vault._read_capped`
    # do — the frontmatter regex is LF-anchored, so without this a CRLF-authored note's declared
    # `source_sha256` is invisible here while the reader saw it. That note would then be counted as
    # checked and listed as `changed` forever: permanently STALE on a vault nobody touched, and
    # recomposing would not clear it. The checksum is still taken over the RAW bytes, as the reader
    # takes it.
    text = data.decode("utf-8", errors="replace").replace("\r\n", "\n").replace("\r", "\n")
    front, _ = _parse_frontmatter(text)
    declared = front.get("source_sha256", "")
    if _SHA256.fullmatch(declared):
        return declared, True
    return hashlib.sha256(data).hexdigest(), False


def _effective_sha(path: Path) -> tuple[str, bool]:
    """`effective_sha_of` for a caller that has only a path."""
    return effective_sha_of(path.read_bytes())


def drift(store, note_paths: list[Path]) -> dict:
    """Compare the notes on disk against what this index holds.

    `note_paths` is the composed scope's note set (`vault.resolve_scope(...).notes`), so "added"
    means a note the manifest composes that the index does not have — which is the case a caller
    most needs, since it looks identical to a question the corpus simply cannot answer.

    Returns counts plus the paths involved, and `stale` — true if ANY of the three differ.
    """
    # BOTH sides are resolved through the same call. They are written by different code paths —
    # the index stores whatever path ingest was handed, the walk produces whatever rglob yields —
    # and on macOS a temp dir alone differs (`/var/...` vs `/private/var/...`). Comparing them
    # unnormalized reported every single note as simultaneously added AND removed: a drift check
    # that cries wolf on a clean vault is worse than none, because its reader learns to ignore it.
    indexed: dict[str, str] = {
        str(Path(r["source_path"]).resolve()): (r["source_sha256"] or "")
        for r in store.db.execute("SELECT source_path, source_sha256 FROM documents")
    }
    on_disk = {str(p.resolve()): p for p in note_paths}

    added = sorted(set(on_disk) - set(indexed))
    removed = sorted(set(indexed) - set(on_disk))

    changed: list[str] = []
    unverifiable = 0
    checked = 0
    unreadable: list[str] = []
    for path_str in sorted(set(indexed) & set(on_disk)):
        try:
            sha, was_declared = _effective_sha(on_disk[path_str])
        except OSError:
            # Indexed, present in the composed set, and unreadable now — neither fresh nor
            # missing, so it gets its own bucket instead of being silently counted as either.
            unreadable.append(path_str)
            continue
        if was_declared:
            # The declaration itself is still comparable, even though the body is not. A note
            # whose frontmatter now names a DIFFERENT source is a change the index can see, and
            # counting it `unverifiable` threw that away — the bucket is for what cannot be
            # checked, not for everything in its neighbourhood.
            if sha != indexed[path_str]:
                changed.append(path_str)
            else:
                unverifiable += 1
            continue
        checked += 1
        if sha != indexed[path_str]:
            changed.append(path_str)

    return {
        # `stale` means something DEFINITELY differs. Unreadable notes are a different statement —
        # nothing is known about them — so they get `checkable` rather than being folded in here,
        # where they would be indistinguishable from a detected change. A consumer must read both:
        # `stale: false, checkable: false` is "no change found, and some notes were not examined".
        "stale": bool(added or removed or changed),
        "checkable": not unreadable,
        "added": added,
        "removed": removed,
        "changed": changed,
        "checked": checked,
        # Notes whose stored checksum is a DECLARED one (it names a PDF, per Doc 2 §3b), so an edit
        # to the note body cannot be detected from the index alone. Named, not folded into
        # "unchanged" — this count is the honest boundary of what `stale: false` means.
        "unverifiable": unverifiable,
        "unreadable": unreadable,
    }
